# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vidservice.protos.protos_definations.video_streaming_pb2 as video__streaming__pb2


class VideoStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getVideoStream = channel.unary_stream(
                '/protos.VideoStreamer/getVideoStream',
                request_serializer=video__streaming__pb2.VideoMetaData.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrames.FromString,
                )
        self.sendVideoStream = channel.stream_unary(
                '/protos.VideoStreamer/sendVideoStream',
                request_serializer=video__streaming__pb2.VideoFrames.SerializeToString,
                response_deserializer=video__streaming__pb2.VideoFrames.FromString,
                )


class VideoStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getVideoStream(self, request, context):
        """Get video stream (watch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendVideoStream(self, request_iterator, context):
        """Send video stream (upload)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getVideoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getVideoStream,
                    request_deserializer=video__streaming__pb2.VideoMetaData.FromString,
                    response_serializer=video__streaming__pb2.VideoFrames.SerializeToString,
            ),
            'sendVideoStream': grpc.stream_unary_rpc_method_handler(
                    servicer.sendVideoStream,
                    request_deserializer=video__streaming__pb2.VideoFrames.FromString,
                    response_serializer=video__streaming__pb2.VideoFrames.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.VideoStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getVideoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/protos.VideoStreamer/getVideoStream',
            video__streaming__pb2.VideoMetaData.SerializeToString,
            video__streaming__pb2.VideoFrames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendVideoStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/protos.VideoStreamer/sendVideoStream',
            video__streaming__pb2.VideoFrames.SerializeToString,
            video__streaming__pb2.VideoFrames.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
